config/routes.rb
Rails.application.routes.draw do
  get 'timelines/index'

  get 'languages/index'

  devise_for :admins
  get 'admin/index', as: "admin"
  
  resources :uploads

  get 'welcome/index'
  get 'welcome/about', as: "about"
  get 'welcome/index', as: "index"
  get 'welcome/services', as: "services"
  get 'uploads/index', as: "uploadsIndex"
  get 'languages/index', as: "languages"
  resources :languages
  get 'timelines/index', as: "timelines"
  resources :timelines

   root 'welcome#index'

  match ':controller(/:action(/:id))', via: :get
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/language.rb
class Language < ActiveRecord::Base
	scope :sorted, -> { order(:position) }
end

app/models/timeline.rb
class Timeline < ActiveRecord::Base
  scope :sorted, -> { order(created_at: :desc) }
  
  has_attached_file :image, styles: { large: "500x500>", medium: "300x300>", thumb: "101x101#" }
  
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
end

app/models/upload.rb
class Upload < ActiveRecord::Base
  scope :sorted, -> { order(created_at: :desc) }

  has_attached_file :image, styles: { large: "500x500>", medium: "300x300>", thumb: "101x101#" }
  
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
 before_action :authenticate_admin!
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/languages_controller.rb
class LanguagesController < ApplicationController
  before_action :authenticate_admin!
  def index
   @language = Language.sorted
  end
  def show
    @language = Language.find(params[:id])
  end
  def new
   @language = Language.new
  end
  def create
    @language = Language.new(language_params)
    if @language.save
      flash[:success] = "Language created successfully"
      redirect_to @language
    else
      render 'new'
    end
  end
  def edit
   @language = Language.find(params[:id])
  end
  def update
    @language = Language.find(params[:id])
    if @language.update_attributes(language_params)
      flash[:success] = "Updated Sucessfully!"
      redirect_to(action: 'index')
    else
      flash[:error] = "Oops! Something went wrong."
      render 'edit'
    end
  end
  def destroy
    @language = Language.find(params[:id])
    @language.destroy
    flash[:success] = "Language deleted successfully"
    redirect_to action: 'index'
  end
   private

    def language_params
      params.require(:language).permit(:name, :position, :visible,
                                   :content_type, :content, :icon)
    end
end

app/controllers/timelines_controller.rb
class TimelinesController < ApplicationController
  before_action :authenticate_admin!
  def index
    @timeline = Timeline.sorted
  end
  def new
    @timeline = Timeline.new
  end
  def create
    @timeline = Timeline.new(timeline_params)
    if @timeline.save
      flash[:success] = "Status created successfully"
      redirect_to @timeline
    else
      render 'new'
    end
  end  
  def edit
   @timeline = Timeline.find(params[:id])
  end
  def update
    @timeline = Timeline.find(params[:id])
    if @timeline.update_attributes(timeline_params)
      flash[:success] = "Updated Sucessfully!"
      redirect_to(action: 'index')
    else
      flash[:error] = "Oops! Something went wrong."
      render 'edit'
    end
  end
  def destroy
    @timeline = Timeline.find(params[:id])
    @timeline.destroy
    flash[:success] = "Status deleted successfully"
    redirect_to action: 'index'
  end
   private

    def timeline_params
      params.require(:timeline).permit(:user, :image, :content)
    end
end

app/controllers/uploads_controller.rb
class UploadsController < ApplicationController
   before_action :authenticate_admin!
  def index
    @upload = Upload.sorted
  end
  def new
    @upload = Upload.new
  end
  def show
    @upload = Upload.find(params[:id])
  end
   def create
    @upload = Upload.create( upload_params )
    if @upload.save
      flash[:success] = 'Image Uploaded Successfully'
      redirect_to @upload
    else
      #  you need to send an error header.
          #  will not interpret the response as an error:
      flash[:success] = 'Upload Failed!'
    end     
  end

  private
  def upload_params
    params.require(:upload).permit(:image)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

	def index
		@languages = Language.sorted
	end
  def about
    @timelines = Timeline.sorted
    @uploads = Upload.sorted
  end
  def services
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/language_helper.rb
module LanguageHelper
end

app/helpers/timelines_helper.rb
module TimelinesHelper
end

app/helpers/uploads_helper.rb
module UploadsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admin/images.html.erb
<p class="navbar-text pull-right">
<% if admin_signed_in? %>
<div class="pull-left">
  <span> Welcome, <strong><%= current_admin.username %></strong>.</span>
  <%= link_to "Logout", destroy_admin_session_path, method: :delete, :class => 'navbar-link' %>
</div>
<br>
<%= form_for(@upload, html: { multipart: true }) do |f|  %>
  <div class="fallback">
    <%= f.file_field :image, required: true, class: 'fileupload' %><br>
    <%= f.submit "Upload", class: 'btn btn-primary' %>
  </div>
<% end %>
<br>

<% end %>

app/views/admin/index.html.erb
<% if flash[:success] != nil %>
<p class="alert alert-success"><%= flash[:success] %></p>
<% end %>
<p class="navbar-text pull-right">
<% if admin_signed_in? %>
<div class="pull-left">
  <span> Welcome, <strong><%= current_admin.username %></strong>.</span>
  <%= link_to "Logout", destroy_admin_session_path, method: :delete, class: 'navbar-link' %>
</div>
<br>
<div class="about">
  <ul>
  <li><%= link_to "Upload Images", uploads_path %></li>
  <li><%= link_to "Coding Languages", languages_path %></li>
  <li><%= link_to "Timeline", timelines_path %></li>
  </ul>
</div>
<% end %>

app/views/languages/create.html.erb
<h1>Create Language Page</h1>

app/views/languages/edit.html.erb
<p class="navbar-text pull-right">
<% if admin_signed_in? %>
<div class="pull-left">
  <span> Welcome, <strong><%= current_admin.username %></strong>.</span>
  <%= link_to "Logout", destroy_admin_session_path, method: :delete, :class => 'navbar-link' %>
</div>
<br>
<% provide(:title, "Edit Language") %>
<h1>Edit coding language information</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@language) do |f| %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>
      <br>
      <%= f.label :position %>
      <%= f.text_field :position, disabled: true, class: 'form-control' %>
      <br>
      <%= f.label :content_type %>
      <%= f.text_field :content_type, class: 'form-control' %>
      <br>
      <%= f.label :content %>
      <%= f.text_area :content, class: 'summernote', id: 'summernote' %>
      <br>
      <%= f.label :icon %>
      <%= f.text_field :icon, class: 'form-control' %>
      <br>
      <%= f.label :visible %>
      <%= f.check_box :visible, class: 'checkbox-default' %>
      <br><br>
      <%= f.submit "Save", class: "btn btn-primary" %> <%= link_to 'Cancel', 'index', class: 'btn btn-default' %>
    <% end %>

  </div>
</div>
<% end %>

app/views/languages/index.html.erb
<% if flash[:success] != nil %>
<p class="alert alert-success"><%= flash[:success] %></p>
<% end %>
<p class="navbar-text pull-right">
<% if admin_signed_in? %>
<div class="pull-left">
  <span> Welcome, <strong><%= current_admin.username %></strong>.</span>
  <%= link_to "Logout", destroy_admin_session_path, method: :delete, :class => 'navbar-link' %>
</div>
<br>
<div class="about">
  <div class="row">
    <div class="col-md-12">
       <section class="panel">
        <header class="panel-heading">
          <h2>Languages</h2>
        </header>
        <div class="panel-body">
          <div class="table-responsive">
            <table class="table mb-none">
              <thead>
                <tr>
                    <th>Name</th>
                      <th>Position</th>
                      <th>Visible</th>
                      <th>Overview</th>
                      <th>Content</th>
                      <th>Icon</th>
                      <th>Actions</th>
                </tr>
              </thead>
                <tbody>
                  
           <% @language.each do |language| %>
            <% @language = Language.find(language.id) %>
                      <tr>
                            <td><%= language.name %></td>
                            <td><%= language.position %></td>
                            <td><%= language.visible %></td>
                            <td><%= language.content_type %></td>
                            <td><%= language.content.html_safe %></td>
                            <td><%= language.icon %></td>
                            <td class="actions">
                              <%= link_to '', edit_language_path(language), class: 'fa fa-pencil' %>
                              <%= link_to '', language, method: :delete, data: {confirm: "You sure?"}, class: 'fa fa-trash-o' %>
                            </td> 
                      </tr>
            <% end %>
                 
                </tbody>
              </table>
            </div>
          </div>
        </section>
      </div>
    </div>   
     <%= link_to 'Add Language', new_language_path, class: 'btn btn-success' %> <%= link_to 'Back', admin_path, class: 'btn btn-default' %>
  </div>
<% end %>

app/views/languages/new.html.erb
<p class="navbar-text pull-right">
<% if admin_signed_in? %>
<div class="pull-left">
  <span> Welcome, <strong><%= current_admin.username %></strong>.</span>
  <%= link_to "Logout", destroy_admin_session_path, method: :delete, :class => 'navbar-link' %>
</div>
<br>
<% provide(:title, "Edit Language") %>
<h1>Edit coding language information</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for @language, url: { action: '' }  do |f| %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>
      <br>
      <%= f.label :position %>
      <%= f.text_field :position, class: 'form-control' %>
      <br>
      <%= f.label :content_type %>
      <%= f.text_field :content_type, class: 'form-control' %>
      <br>
      <%= f.label :content %>
      <%= f.text_area :content, class: 'summernote', id: 'summernote' %>
      <br>
      <%= f.label :icon %>
      <%= f.text_field :icon, class: 'form-control' %>
      <br>
      <%= f.label :visible %>
      <%= f.check_box :visible, class: 'checkbox-default' %>
      <br><br>
      <%= f.submit "Save", class: "btn btn-primary" %> <%= link_to 'Cancel', 'index', class: 'btn btn-default' %>
    <% end %>
  </div>
</div>
<% end %>

app/views/languages/show.html.erb
<%= @language.name %>, <%= @language.content.html_safe %>
<br>
<%= link_to 'Back', 'index', class: 'btn btn-success' %>

app/views/languages/update.html.erb
<h1>Updated Successfully</h1>

app/views/layouts/_footer.html.erb
    <!-- Footer -->
    <footer>
        <div id="contact" class="container">
            <div class="row">
                <div class="col-lg-10 col-lg-offset-1 text-center">
                    <h4><strong>Contact Information</strong>
                    </h4>
                    <p>University Area<br>Charlotte, NC 28213</p>
                    <ul class="list-unstyled">
                        <li><i class="fa fa-phone fa-fw"></i><a href="tel:1-704-819-4376">+1(704) 819-4376</a></li>
                        <li><i class="fa fa-envelope-o fa-fw"></i>  <a href="mailto:abdelfa@icloud.com">abdelfa@icloud.com</a>
                        </li>
                    </ul>
                    <br>
                    <ul class="list-inline">
                        <li>
                            <a href="https://www.linkedin.com/in/aabdelfa"><i class="fa fa-linkedin fa-fw fa-3x"></i></a>
                        </li>
                        <li>
                            <a href="https://www.facebook.com/alaa.e.hassan.7"><i class="fa fa-facebook fa-fw fa-3x"></i></a>
                        </li>
                        <li>
                            <a href="https://github.com/aabdelfa"><i class="fa fa-github fa-fw fa-3x"></i></a>
                        </li>
                    </ul>
                    <hr class="small">
                    <p class="text-muted">Copyright &copy; Meet-Al 2014</p>
                </div>
            </div>
        </div>
    </footer>

 <!-- Map -->
    <section class="map">
        <iframe width="100%" height="100%" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d164737.486255989!2d-80.86603426468962!3d35.30336945682845!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x88541958da31e23f%3A0x2b0797205a6a9205!2sBack+Creek+Church+Rd%2C+Charlotte%2C+NC!5e0!3m2!1sen!2sus!4v1453219873633"></iframe>
        <br />

        </iframe>
    </section>


    <!-- Custom Theme JavaScript -->
    <script>
    $(document).ready(function() {
    $('#summernote').summernote({height: 300});
    });
    // Closes the sidebar menu
    $("#menu-close").click(function(e) {
        e.preventDefault();
        $("#sidebar-wrapper").toggleClass("active");
    });

    // Opens the sidebar menu
    $("#menu-toggle").click(function(e) {
        e.preventDefault();
        $("#sidebar-wrapper").toggleClass("active");
    });

    // Scrolls to the selected menu item on the page
    $(function() {
        $('a[href*=#]:not([href=#])').click(function() {
            if (location.pathname.replace(/^\//, '') == this.pathname.replace(/^\//, '') || location.hostname == this.hostname) {

                var target = $(this.hash);
                target = target.length ? target : $('[name=' + this.hash.slice(1) + ']');
                if (target.length) {
                    $('html,body').animate({
                        scrollTop: target.offset().top
                    }, 1000);
                    return false;
                }
            }
        });
    });
    </script>

</body>

</html>

app/views/layouts/_header.html.erb
 <!-- Header -->
    <header id="top" class="header">
      
        <div class="text-vertical-center">
          <div "col-md-12 col-lg-12 text-center">
      </div>
            <h1 class="for-dark-bg" >Welcome</h1>
            <h3 class="for-dark-bg">Meet Al</h3>
            <br>
            <a href="#about" class="btn btn-dark btn-lg">Find Out More</a>
        </div>
    </header>

app/views/layouts/_nav.html.erb
<!-- Navigation -->
    <a id="menu-toggle" href="#" class="btn btn-dark btn-lg toggle"><i class="fa fa-bars"></i></a>
    <nav id="sidebar-wrapper">
        <ul class="sidebar-nav">
            <a id="menu-close" href="#" class="btn btn-light btn-lg pull-right toggle"><i class="fa fa-times"></i></a>
            <li class="sidebar-brand">
                <a href="#top"  onclick = $("#menu-close").click(); >Meet Al</a>
            </li>
            <li>
                <%= link_to("Home",index_path) %>
            </li>
            <li>
                <%= link_to("About",about_path) %>
            </li>
            <li>
                 <%= link_to("Services",services_path) %>
            </li>
            <li>
                <a href="#contact" onclick = $("#menu-close").click(); >Contact</a>
            </li>
        </ul>
    </nav>

app/views/timelines/edit.html.erb
<p class="navbar-text pull-right">
<% if admin_signed_in? %>
<div class="pull-left">
  <span> Welcome, <strong><%= current_admin.username %></strong>.</span>
  <%= link_to "Logout", destroy_admin_session_path, method: :delete, :class => 'navbar-link' %>
</div>
<br>
<% provide(:title, "Edit timeline") %>
<h1>Edit timeline information</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@timeline) do |f| %>

      <%= f.label :user %>
      <%= f.text_field :user, class: 'form-control' %>
      <br>
      <%= f.label :image %>
      <%= f.text_field :image, class: 'form-control' %>
      <br>
      <%= f.label :content %>
      <%= f.text_field :content, class: 'form-control' %>
      <br><br>
      <%= f.submit "Save", class: "btn btn-primary" %> <%= link_to 'Cancel', 'index', class: 'btn btn-default' %>
    <% end %>

  </div>
</div>
<% end %>

app/views/timelines/index.html.erb
<% if flash[:success] != nil %>
<p class="alert alert-success"><%= flash[:success] %></p>
<% end %>
<p class="navbar-text pull-right">
<% if admin_signed_in? %>
<div class="pull-left">
  <span> Welcome, <strong><%= current_admin.username %></strong>.</span>
  <%= link_to "Logout", destroy_admin_session_path, method: :delete, class: 'navbar-link' %>
</div>
<br>
<div class="about">
  <div class="row">
    <div class="col-md-12">
       <section class="panel">
        <header class="panel-heading">
          <h2>Timelines</h2>
        </header>
        <div class="panel-body">
          <div class="table-responsive">
            <table class="table mb-none">
              <thead>
                <tr>
                    <th>User</th>
                    <th>Images</th>
                    <th>Content</th>
                    <th>Created</th>
                </tr>
              </thead>
                <tbody>
                  
           <% @timeline.each do |timeline| %>
                      <tr>
                            <td><%= timeline.user %></td>
                            <td>
                            <% if timeline.image.url == '/images/original/missing.png' %>
                              No image available.
                                <% else %>
                                <a data-toggle="modal" data-target="#id<%= timeline.id %>" class="btn btn-light"><%= image_tag timeline.image.url(:thumb) %></a>
                                <div id="id<%= timeline.id %>" class="modal fade" role="dialog">
                                  <div class="modal-dialog">
                                    <!-- Modal content-->                 
                                        <%= image_tag timeline.image.url(:large) %>
                                    </div>
                                  </div>
                             <% end %>
                             </td>   
                            <td><%= timeline.content %></td>
                            <td><%= timeline.created_at.strftime("%B %Y, %d at %l:%M %p") %></td>
                            <td class="actions">
                              <%= link_to '', edit_timeline_path(timeline), class: 'fa fa-pencil' %>
                              <%= link_to '', timeline, method: :delete, data: {confirm: "You sure?"}, class: 'fa fa-trash-o' %>
                            </td> 
                      </tr>
            <% end %>
                </tbody>
              </table>
            </div>
          </div>
        </section>
      </div> 
    </div>  
     <%= link_to 'Add Status', new_timeline_path, class: 'btn btn-success' %> <%= link_to 'Back', admin_path, class: 'btn btn-default' %> 
  </div>
<% end %>

app/views/timelines/new.html.erb
<p class="navbar-text pull-right">
<% if admin_signed_in? %>
<div class="pull-left">
  <span> Welcome, <strong><%= current_admin.username %></strong>.</span>
  <%= link_to "Logout", destroy_admin_session_path, method: :delete, :class => 'navbar-link' %>
</div>
<br>
<% provide(:title, "Edit timeline") %>
<h1>Edit coding timeline information</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for @timeline, url: { action: '' }  do |f| %>

      <%= f.label :user %>
      <%= f.text_field :user, default: 'Alaa', disabled: true, class: 'form-control' %>
      <br>
      <%= f.label :image %>
      <%= f.file_field :image, class: 'fileupload' %><br>
      <br>
      <%= f.label :content %>
      <%= f.text_field :content, class: 'form-control' %>
      <br><br>
      <%= f.submit "Save", class: "btn btn-primary" %> <%= link_to 'Cancel', 'index', class: 'btn btn-default' %>
    <% end %>
  </div>
</div>
<% end %>

app/views/timelines/show.html.erb
Show page for timeline

app/views/uploads/create.html.erb
Create Page
<%= link_to 'Back', 'index', class: 'btn btn-success' %>

app/views/uploads/index.html.erb
<% if flash[:success] != nil %>
<p class="alert alert-success"><%= flash[:success] %></p>
<% end %>
<p class="navbar-text pull-right">
<% if admin_signed_in? %>
<div class="pull-left">
  <span> Welcome, <strong><%= current_admin.username %></strong>.</span>
  <%= link_to "Logout", destroy_admin_session_path, method: :delete, :class => 'navbar-link' %>
</div>
<br>
<div class="about">
  <div class="row">
    <div class="col-md-12">
       <section class="panel">
        <header class="panel-heading">
          <h2>Images</h2>
        </header>
        <div class="panel-body">
          <div class="table-responsive">
            <table class="table mb-none">
              <thead>
                <tr>
                    <th>Image</th>
                    <th>Type</th>
                    <th>File Name</th>
                    <th>Created</th>
                    <th>Actions</th>
                </tr>
              </thead>
                <tbody>
                  
           <% @upload.each do |image| %>
            <% @upload = Upload.find(image.id) %>
                      <tr>
                            <td><%= image_tag image.image.url(:thumb) %></td>
                            <td><%= image.image_content_type %></td>
                            <td><%= image.image_file_name %></td>
                            <td><%= image.created_at %></td>
                            <td class="actions">
                              
                              <a href="" class="delete-row"><i class="fa fa-trash-o"></i></a>
                            </td> 
                      </tr>
            <% end %>
                 
                </tbody>
              </table>
            </div>
          </div>
        </section>
      </div>
    </div>   
     <%= link_to 'New Image', new_upload_path, class: 'btn btn-success' %> <%= link_to 'Back', admin_path, class: 'btn btn-default' %>
  </div>
<% end %>

app/views/uploads/new.html.erb
<p class="navbar-text pull-right">
<% if admin_signed_in? %>
<div class="pull-left">
  <span> Welcome, <strong><%= current_admin.username %></strong>.</span>
  <%= link_to "Logout", destroy_admin_session_path, method: :delete, :class => 'navbar-link' %>
</div>
<br>
<%= form_for @upload, url: uploads_path, html: { multipart: true } do |f|  %>
  <div class="fallback">
    <%= f.label :image %><br>
    <%= f.file_field :image, required: true, class: 'fileupload' %><br>
    <%= f.submit "Upload", class: 'btn btn-primary' %>
  </div>
<% end %>
<br>

<% end %>

app/views/welcome/index.html.erb
<!DOCTYPE html>
<html lang="en">
<body>
    <script>
    /* This is for including Facebook
  window.fbAsyncInit = function() {
    FB.init({
      appId      : '827100840769217',
      xfbml      : true,
      version    : 'v2.5'
    });
  };

  (function(d, s, id){
     var js, fjs = d.getElementsByTagName(s)[0];
     if (d.getElementById(id)) {return;}
     js = d.createElement(s); js.id = id;
     js.src = "//connect.facebook.net/en_US/sdk.js";
     fjs.parentNode.insertBefore(js, fjs);
   }(document, 'script', 'facebook-jssdk')); */
</script>
    <!-- About -->
    <section id="about" class="about">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <h2>Here you can view my portfolio, all the work I've done and know all about me.</h2>
                     <p class="lead">About me -  <%= link_to("Click Here",about_path) %></p>
                </div>
            </div>
            <!-- /.row -->
        </div>
        <!-- /.container -->
    </section>
<div
  class="fb-like"
  data-share="true"
  data-width="450"
  data-show-faces="true">
</div>
    <!-- Services -->
    <!-- The circle icons use Font Awesome's stacked icon classes. For more information, visit http://fontawesome.io/examples/ -->
    <section id="services" class="services bg-primary">
        <div class="container">
            <div class="row text-center">
                <div class="col-lg-10 col-lg-offset-1">
                    <h2>My Projects with...</h2>
                    <hr class="small">
                    <div class="row">
                        <% @languages.each do |language| %>
                        <div class="col-md-3 col-sm-6">
                            <div class="service-item">
                                <span class="fa-stack fa-4x">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="<%= language.icon %> fa-stack-1x text-primary"></i>
                                </span>
                                <h4>
                                    <strong><%= language.name %></strong>
                                </h4>
                                <p><%= language.content_type %></p>
                                <a data-toggle="modal" data-target="#id<%= language.id %>" class="btn btn-light">Learn More</a>
                            </div>
                        </div>
                        <div id="id<%= language.id %>" class="modal fade" role="dialog">
                          <div class="modal-dialog">

                            <!-- Modal content-->
                            <div class="modal-content">
                              <div class="modal-header">
                                <button type="button" class="close" data-dismiss="modal">&times;</button>
                                <h4 class="modal-title text-primary">Project(s) created with <%= language.name %></h4>
                              </div>
                              <div class="modal-body" style="color: #191919;">
                                <%= language.content.html_safe %>
                              </div>
                              <div class="modal-footer">
                                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                              </div>
                            </div>

                          </div>
                        </div>

                        <% end %>
                    </div>
                    <!-- /.row (nested) -->
                </div>
                <!-- /.col-lg-10 -->
            </div>
            <!-- /.row -->
        </div>
        <!-- /.container -->
    </section>

    <!-- Callout -->
    <aside class="callout">
        <div class="text-vertical-center">
            <h1>Quick facts about Al</h1>
            <div class="col-md-4"></div>
            <div class="col-md-6">
               <ul class="text-left">
                  <li><h3>Went to college at the age of 16.</h3></li>
                  <li><h3>Graduated high school from Cambridge University.</h3></li>
                  <li><h3>Played soccer professionally.</h3></li>
                  <li><h3>Collects old and rare coins.</h3></li>
                  <li><h3>Moved to the United States by himself 5 years ago.</h3></li>
               </ul>
            </div> 
        </div>
    </aside>

    <!-- Portfolio -->
    <section id="portfolio" class="portfolio">
        <div class="container">
            <div class="row">
                <div class="col-lg-10 col-lg-offset-1 text-center">
                    <h2>My Work</h2>
                    <hr class="small">
                    <div class="row">
                        <div class="col-md-6">
                            <div class="portfolio-item">
                                <a href="#">
                                   <%= link_to image_tag("portfolio-1.jpg"), 'http://abundantpower.com', target: '_blank' %>
                                </a>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="portfolio-item">
                                <a href="#">
                                   <%= link_to image_tag("portfolio-2.jpg"), 'http://ibaxportal.com', target: '_blank' %>
                                </a>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="portfolio-item">
                                <a href="#">
                                   <%= link_to image_tag("portfolio-3.jpg") %>
                                </a>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="portfolio-item">
                                
                                   <%= link_to image_tag("portfolio-4.jpg"), 'http://pre.ezzy-statistics.com', target: '_blank' %>
                             
                            </div>
                        </div>
                    </div>
                    <!-- /.row (nested) -->
                </div>
                <!-- /.col-lg-10 -->
            </div>
            <!-- /.row -->
        </div>
        <!-- /.container -->
    </section>

    <!-- Call to Action -->
    <aside class="call-to-action bg-primary">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <h3>If you like my work and would like to checkout my services</h3>
                    <%= link_to("Click Here!",services_path, class: 'btn btn-lg btn-light') %>
                    <a href="#contact" class="btn btn-lg btn-dark">Contact directly!</a>
                </div>
            </div>
        </div>
    </aside>